"""Country lookup data for location parsing. Data, not logic — extend by adding rows."""

COUNTRY_NAME_TO_CODE: dict[str, str] = {
    "australia": "AU",
    "austria": "AT",
    "belgium": "BE",
    "brazil": "BR",
    "canada": "CA",
    "china": "CN",
    "czech republic": "CZ",
    "czechia": "CZ",
    "denmark": "DK",
    "egypt": "EG",
    "estonia": "EE",
    "finland": "FI",
    "france": "FR",
    "germany": "DE",
    "greece": "GR",
    "hong kong": "HK",
    "hungary": "HU",
    "india": "IN",
    "indonesia": "ID",
    "ireland": "IE",
    "israel": "IL",
    "italy": "IT",
    "japan": "JP",
    "korea": "KR",
    "south korea": "KR",
    "latvia": "LV",
    "lithuania": "LT",
    "luxembourg": "LU",
    "malaysia": "MY",
    "mexico": "MX",
    "netherlands": "NL",
    "the netherlands": "NL",
    "new zealand": "NZ",
    "norway": "NO",
    # NAV's register writes the country in Norwegian ("NORGE"); a foreign ad written in
    # Norwegian stays country-less until its name is observed and added here (SPEC: never
    # fabricate a country).
    "norge": "NO",
    "philippines": "PH",
    "poland": "PL",
    "portugal": "PT",
    "romania": "RO",
    "singapore": "SG",
    "slovakia": "SK",
    "spain": "ES",
    "sweden": "SE",
    "switzerland": "CH",
    "taiwan": "TW",
    "thailand": "TH",
    "turkey": "TR",
    "ukraine": "UA",
    "united arab emirates": "AE",
    "uae": "AE",
    "uk": "GB",
    "united kingdom": "GB",
    "great britain": "GB",
    "england": "GB",
    "scotland": "GB",
    "usa": "US",
    "united states": "US",
    "united states of america": "US",
    "u.s.": "US",
    "u.s.a.": "US",
    "vietnam": "VN",
}

US_STATE_CODES: frozenset[str] = frozenset(
    {
        "AL",
        "AK",
        "AZ",
        "AR",
        "CA",
        "CO",
        "CT",
        "DE",
        "FL",
        "GA",
        "HI",
        "ID",
        "IL",
        "IN",
        "IA",
        "KS",
        "KY",
        "LA",
        "ME",
        "MD",
        "MA",
        "MI",
        "MN",
        "MS",
        "MO",
        "MT",
        "NE",
        "NV",
        "NH",
        "NJ",
        "NM",
        "NY",
        "NC",
        "ND",
        "OH",
        "OK",
        "OR",
        "PA",
        "RI",
        "SC",
        "SD",
        "TN",
        "TX",
        "UT",
        "VT",
        "VA",
        "WA",
        "WV",
        "WI",
        "WY",
        "DC",
    }
)

# Multi-country regions that must never be mistaken for a city.
US_STATE_NAMES: frozenset[str] = frozenset(
    {
        "alabama",
        "alaska",
        "arizona",
        "arkansas",
        "california",
        "colorado",
        "connecticut",
        "delaware",
        "district of columbia",
        "florida",
        "georgia",
        "hawaii",
        "idaho",
        "illinois",
        "indiana",
        "iowa",
        "kansas",
        "kentucky",
        "louisiana",
        "maine",
        "maryland",
        "massachusetts",
        "michigan",
        "minnesota",
        "mississippi",
        "missouri",
        "montana",
        "nebraska",
        "nevada",
        "new hampshire",
        "new jersey",
        "new mexico",
        "new york",
        "north carolina",
        "north dakota",
        "ohio",
        "oklahoma",
        "oregon",
        "pennsylvania",
        "rhode island",
        "south carolina",
        "south dakota",
        "tennessee",
        "texas",
        "utah",
        "vermont",
        "virginia",
        "washington",
        "west virginia",
        "wisconsin",
        "wyoming",
    }
)
"""Spelled-out US states. Only ever read in a *qualified* position — a comma tail
("Austin, Texas") or a delimiter part ("Remote - California") — never as a bare lone token,
because "Georgia" and "Washington" name more than one thing and a lone one must not pick."""


REGION_TOKENS: frozenset[str] = frozenset(
    {
        "africa",
        "americas",
        "apac",
        "asia",
        "asia pacific",
        "emea",
        "europe",
        "global",
        "latam",
        "latin america",
        "middle east",
        "north america",
        "oceania",
        "remote",
        "south america",
        "worldwide",
    }
)

NON_CITY_TOKENS: frozenset[str] = REGION_TOKENS | frozenset(
    {
        # Compass and arrangement words a board writes where a city would go.
        "east",
        "west",
        "north",
        "south",
        "central",
        "northeast",
        "northwest",
        "southeast",
        "southwest",
        "hybrid",
        "onsite",
        "on-site",
        "in-office",
        "office",
        # Placeholders. "Anywhere in the World" is not a city, and neither is "N/A".
        "amer",
        "anywhere",
        "anywhere in the world",
        "n/a",
        "na",
        "tbd",
        "unspecified",
    }
)
"""Everything REGION_TOKENS covers, plus the words that occupy a city slot without naming
a place. Read wherever a candidate city is accepted, so junk never lands in the column."""
