"""Country lookup data for location parsing. Data, not logic — extend by adding rows."""

COUNTRY_NAME_TO_CODE: dict[str, str] = {
    "australia": "AU",
    "austria": "AT",
    "belgium": "BE",
    "brazil": "BR",
    "canada": "CA",
    "china": "CN",
    "czech republic": "CZ",
    "czechia": "CZ",
    "denmark": "DK",
    "egypt": "EG",
    "estonia": "EE",
    "finland": "FI",
    "france": "FR",
    "germany": "DE",
    "greece": "GR",
    "hong kong": "HK",
    "hungary": "HU",
    "india": "IN",
    "indonesia": "ID",
    "ireland": "IE",
    "israel": "IL",
    "italy": "IT",
    "japan": "JP",
    "korea": "KR",
    "south korea": "KR",
    "latvia": "LV",
    "lithuania": "LT",
    "luxembourg": "LU",
    "malaysia": "MY",
    "mexico": "MX",
    "netherlands": "NL",
    "the netherlands": "NL",
    "new zealand": "NZ",
    "norway": "NO",
    # NAV's register writes the country in Norwegian ("NORGE"); a foreign ad written in
    # Norwegian stays country-less until its name is observed and added here (SPEC: never
    # fabricate a country).
    "norge": "NO",
    "philippines": "PH",
    "poland": "PL",
    "portugal": "PT",
    "romania": "RO",
    "singapore": "SG",
    "slovakia": "SK",
    "spain": "ES",
    "sweden": "SE",
    "switzerland": "CH",
    "taiwan": "TW",
    "thailand": "TH",
    "turkey": "TR",
    "ukraine": "UA",
    "united arab emirates": "AE",
    "uae": "AE",
    "uk": "GB",
    "united kingdom": "GB",
    "great britain": "GB",
    "england": "GB",
    "scotland": "GB",
    "usa": "US",
    "united states": "US",
    "united states of america": "US",
    "u.s.": "US",
    "u.s.a.": "US",
    "vietnam": "VN",
    # Observed in the corpus as an unresolved comma tail or a bare token, and each one
    # names its country as plainly as the rows above. Extend the same way: only when a
    # real posting has written the name.
    "argentina": "AR",
    "bangladesh": "BD",
    "bulgaria": "BG",
    "chile": "CL",
    "colombia": "CO",
    "costa rica": "CR",
    "croatia": "HR",
    "cyprus": "CY",
    "ecuador": "EC",
    "iraq": "IQ",
    "kenya": "KE",
    "lebanon": "LB",
    "morocco": "MA",
    "nigeria": "NG",
    "pakistan": "PK",
    "peru": "PE",
    "qatar": "QA",
    "saudi arabia": "SA",
    "serbia": "RS",
    "slovenia": "SI",
    "south africa": "ZA",
    "sri lanka": "LK",
    "trinidad and tobago": "TT",
    "uruguay": "UY",
    # Jobtech writes the country in Swedish, as NAV's register writes it in Norwegian.
    "spanien": "ES",
    "sverige": "SE",
}

US_STATE_CODES: frozenset[str] = frozenset(
    {
        "AL",
        "AK",
        "AZ",
        "AR",
        "CA",
        "CO",
        "CT",
        "DE",
        "FL",
        "GA",
        "HI",
        "ID",
        "IL",
        "IN",
        "IA",
        "KS",
        "KY",
        "LA",
        "ME",
        "MD",
        "MA",
        "MI",
        "MN",
        "MS",
        "MO",
        "MT",
        "NE",
        "NV",
        "NH",
        "NJ",
        "NM",
        "NY",
        "NC",
        "ND",
        "OH",
        "OK",
        "OR",
        "PA",
        "RI",
        "SC",
        "SD",
        "TN",
        "TX",
        "UT",
        "VT",
        "VA",
        "WA",
        "WV",
        "WI",
        "WY",
        "DC",
    }
)

# Multi-country regions that must never be mistaken for a city.
US_STATE_NAMES: frozenset[str] = frozenset(
    {
        "alabama",
        "alaska",
        "arizona",
        "arkansas",
        "california",
        "colorado",
        "connecticut",
        "delaware",
        "district of columbia",
        "florida",
        "georgia",
        "hawaii",
        "idaho",
        "illinois",
        "indiana",
        "iowa",
        "kansas",
        "kentucky",
        "louisiana",
        "maine",
        "maryland",
        "massachusetts",
        "michigan",
        "minnesota",
        "mississippi",
        "missouri",
        "montana",
        "nebraska",
        "nevada",
        "new hampshire",
        "new jersey",
        "new mexico",
        "new york",
        "north carolina",
        "north dakota",
        "ohio",
        "oklahoma",
        "oregon",
        "pennsylvania",
        "rhode island",
        "south carolina",
        "south dakota",
        "tennessee",
        "texas",
        "utah",
        "vermont",
        "virginia",
        "washington",
        "west virginia",
        "wisconsin",
        "wyoming",
    }
)
"""Spelled-out US states. Only ever read in a *qualified* position — a comma tail
("Austin, Texas") or a delimiter part ("Remote - California") — never as a bare lone token,
because "Georgia" and "Washington" name more than one thing and a lone one must not pick."""


REGION_TOKENS: frozenset[str] = frozenset(
    {
        "africa",
        "americas",
        "apac",
        "asia",
        "asia pacific",
        "emea",
        "europe",
        "global",
        "latam",
        "latin america",
        "middle east",
        "north america",
        "oceania",
        "remote",
        "south america",
        "worldwide",
    }
)

NON_CITY_TOKENS: frozenset[str] = REGION_TOKENS | frozenset(
    {
        # Compass and arrangement words a board writes where a city would go.
        "east",
        "west",
        "north",
        "south",
        "central",
        "northeast",
        "northwest",
        "southeast",
        "southwest",
        "hybrid",
        "onsite",
        "on-site",
        "in-office",
        "office",
        # Placeholders. "Anywhere in the World" is not a city, and neither is "N/A".
        "amer",
        "anywhere",
        "anywhere in the world",
        "n/a",
        "na",
        "tbd",
        "unspecified",
    }
)
"""Everything REGION_TOKENS covers, plus the words that occupy a city slot without naming
a place. Read wherever a candidate city is accepted, so junk never lands in the column."""


CITY_TO_COUNTRY: dict[str, tuple[str, ...]] = {
    # Every city a board writes bare, ranked by the real corpus so effort lands where the
    # jobs are. The value is a *tuple* because ambiguity is the normal case, not the
    # exception: a name shared by two countries resolves nothing on its own and waits for
    # the employer's home market to break the tie.
    #
    # Shared names — the trap this table exists to survive. Never resolved alone.
    #
    # A name earns a second candidate only when *both* places plausibly host jobs. The
    # test is employment, not cartography: Toronto, Ohio (pop. 5,000) and Paris, Texas
    # (pop. 25,000) share a name with nothing else, so "toronto" and "paris" sit below
    # with the plain rows. Measured over the corpus, listing those two and London here
    # let the employer's home market answer for them and got 27 of 81 rows wrong — every
    # one a multinational advertising outside its home country, which an HQ cannot see.
    "athens": ("GR", "US"),  # Athens, Georgia — pop. 127,000, a university town
    "birmingham": ("GB", "US"),  # Birmingham, Alabama — pop. 200,000
    "cambridge": ("GB", "US"),  # Cambridge, Massachusetts — Kendall Square
    "geneva": ("CH", "US"),  # Geneva, Illinois — a Chicago exurb that does hire
    "manchester": ("GB", "US"),  # Manchester, New Hampshire — pop. 115,000
    "melbourne": ("AU", "US"),  # Melbourne, Florida — the Space Coast employers
    "san jose": ("US", "CR"),  # San José, Costa Rica — a real outsourcing hub
    "vancouver": ("CA", "US"),  # Vancouver, Washington — pop. 190,000
    # United States
    "ann arbor": ("US",),
    "atlanta": ("US",),
    "austin": ("US",),
    "bay area": ("US",),
    "boston": ("US",),
    "brooklyn": ("US",),
    "chicago": ("US",),
    "dallas": ("US",),
    "denver": ("US",),
    "detroit": ("US",),
    "houston": ("US",),
    "kansas city": ("US",),
    "los angeles": ("US",),
    "menlo park": ("US",),
    "miami": ("US",),
    "minneapolis": ("US",),
    "mountain view": ("US",),
    "nashville": ("US",),
    "new york": ("US",),
    "new york city": ("US",),
    "nyc": ("US",),
    "palo alto": ("US",),
    "philadelphia": ("US",),
    "phoenix": ("US",),
    "pittsburgh": ("US",),
    "portland": ("US",),
    "redwood city": ("US",),
    "salt lake city": ("US",),
    "san diego": ("US",),
    "san francisco": ("US",),
    "san francisco bay area": ("US",),
    "san mateo": ("US",),
    "seattle": ("US",),
    "sf bay area": ("US",),
    "sunnyvale": ("US",),
    "washington d.c.": ("US",),
    "washington dc": ("US",),
    # Canada
    "burnaby": ("CA",),
    "calgary": ("CA",),
    "edmonton": ("CA",),
    "halifax": ("CA",),
    "kitchener": ("CA",),
    "kitchener-waterloo": ("CA",),
    "mississauga": ("CA",),
    "montreal": ("CA",),
    "toronto": ("CA",),
    "montréal": ("CA",),
    "ottawa": ("CA",),
    "quebec city": ("CA",),
    "québec": ("CA",),
    "winnipeg": ("CA",),
    # Netherlands
    "amsterdam": ("NL",),
    "delft": ("NL",),
    "den haag": ("NL",),
    "eindhoven": ("NL",),
    "groningen": ("NL",),
    "haarlem": ("NL",),
    "maastricht": ("NL",),
    "rotterdam": ("NL",),
    "the hague": ("NL",),
    "utrecht": ("NL",),
    # Sweden
    "gothenburg": ("SE",),
    "göteborg": ("SE",),
    "linköping": ("SE",),
    "lund": ("SE",),
    "malmo": ("SE",),
    "malmö": ("SE",),
    "stockholm": ("SE",),
    "stockholm hq": ("SE",),
    "uppsala": ("SE",),
    # Denmark, Norway, Finland
    "aalborg": ("DK",),
    "aarhus": ("DK",),
    "copenhagen": ("DK",),
    "kobenhavn": ("DK",),
    "københavn": ("DK",),
    "odense": ("DK",),
    "bergen": ("NO",),
    "oslo": ("NO",),
    "stavanger": ("NO",),
    "trondheim": ("NO",),
    "espoo": ("FI",),
    "helsinki": ("FI",),
    "oulu": ("FI",),
    "tampere": ("FI",),
    "turku": ("FI",),
    # Switzerland, Austria, Belgium
    "basel": ("CH",),
    "bern": ("CH",),
    "lausanne": ("CH",),
    "lugano": ("CH",),
    "zurich": ("CH",),
    "zürich": ("CH",),
    "graz": ("AT",),
    "innsbruck": ("AT",),
    "linz": ("AT",),
    "salzburg": ("AT",),
    "vienna": ("AT",),
    "wien": ("AT",),
    "antwerp": ("BE",),
    "antwerpen": ("BE",),
    "brussels": ("BE",),
    "bruxelles": ("BE",),
    "gent": ("BE",),
    "ghent": ("BE",),
    "leuven": ("BE",),
    # Germany
    "berlin": ("DE",),
    "cologne": ("DE",),
    "dresden": ("DE",),
    "dusseldorf": ("DE",),
    "düsseldorf": ("DE",),
    "frankfurt": ("DE",),
    "hamburg": ("DE",),
    "karlsruhe": ("DE",),
    "köln": ("DE",),
    "leipzig": ("DE",),
    "munich": ("DE",),
    "münchen": ("DE",),
    "nuremberg": ("DE",),
    "stuttgart": ("DE",),
    # France
    "bordeaux": ("FR",),
    "grenoble": ("FR",),
    "lille": ("FR",),
    "lyon": ("FR",),
    "marseille": ("FR",),
    "montpellier": ("FR",),
    "nantes": ("FR",),
    "paris": ("FR",),
    "nice": ("FR",),
    "rennes": ("FR",),
    "sophia antipolis": ("FR",),
    "toulouse": ("FR",),
    # United Kingdom and Ireland
    "belfast": ("GB",),
    "bristol": ("GB",),
    "cardiff": ("GB",),
    "edinburgh": ("GB",),
    "glasgow": ("GB",),
    "leeds": ("GB",),
    "liverpool": ("GB",),
    "nottingham": ("GB",),
    "london": ("GB",),
    "sheffield": ("GB",),
    "cork": ("IE",),
    # Dublin, Ohio and Dublin, California are real places, but a bare "Dublin" in a tech
    # ad is Ireland — 26 of the 28 in the corpus are one employer's Irish engineering hub.
    "dublin": ("IE",),
    "galway": ("IE",),
    "limerick": ("IE",),
    # Iberia and Italy
    "barcelona": ("ES",),
    "bilbao": ("ES",),
    "madrid": ("ES",),
    "malaga": ("ES",),
    "málaga": ("ES",),
    "seville": ("ES",),
    "sevilla": ("ES",),
    "valencia": ("ES",),
    "zaragoza": ("ES",),
    "braga": ("PT",),
    "coimbra": ("PT",),
    "lisboa": ("PT",),
    "lisbon": ("PT",),
    "porto": ("PT",),
    "bologna": ("IT",),
    "firenze": ("IT",),
    "florence": ("IT",),
    "milan": ("IT",),
    "milano": ("IT",),
    "naples": ("IT",),
    "napoli": ("IT",),
    "roma": ("IT",),
    "rome": ("IT",),
    "torino": ("IT",),
    "turin": ("IT",),
    # Central and Eastern Europe
    "brno": ("CZ",),
    "ostrava": ("CZ",),
    "praha": ("CZ",),
    "prague": ("CZ",),
    "gdansk": ("PL",),
    "gdańsk": ("PL",),
    "katowice": ("PL",),
    "krakow": ("PL",),
    "kraków": ("PL",),
    "lodz": ("PL",),
    "poznan": ("PL",),
    "poznań": ("PL",),
    "warsaw": ("PL",),
    "warszawa": ("PL",),
    "wroclaw": ("PL",),
    "wrocław": ("PL",),
    "łódź": ("PL",),
    "budapest": ("HU",),
    "debrecen": ("HU",),
    "bratislava": ("SK",),
    "kosice": ("SK",),
    "košice": ("SK",),
    "bucharest": ("RO",),
    "bucurești": ("RO",),
    "cluj": ("RO",),
    "cluj-napoca": ("RO",),
    "iasi": ("RO",),
    "iași": ("RO",),
    "timisoara": ("RO",),
    "timișoara": ("RO",),
    "plovdiv": ("BG",),
    "sofia": ("BG",),
    "varna": ("BG",),
    "beograd": ("RS",),
    "belgrade": ("RS",),
    "novi sad": ("RS",),
    "zagreb": ("HR",),
    "ljubljana": ("SI",),
    "thessaloniki": ("GR",),
    "ankara": ("TR",),
    "istanbul": ("TR",),
    "izmir": ("TR",),
    "dnipro": ("UA",),
    "kharkiv": ("UA",),
    "kiev": ("UA",),
    "kyiv": ("UA",),
    "lviv": ("UA",),
    "odesa": ("UA",),
    "kaunas": ("LT",),
    "vilnius": ("LT",),
    "riga": ("LV",),
    "tallinn": ("EE",),
    "tartu": ("EE",),
    # South and Southeast Asia. Indonesia is the home market, so its rows decide whether a
    # job is `not_required` — see the sponsorship tier chain.
    "ahmedabad": ("IN",),
    "bangalore": ("IN",),
    "bengaluru": ("IN",),
    "chandigarh": ("IN",),
    "chennai": ("IN",),
    "coimbatore": ("IN",),
    "dehradun": ("IN",),
    "delhi": ("IN",),
    "gurgaon": ("IN",),
    "gurugram": ("IN",),
    "hyderabad": ("IN",),
    "indore": ("IN",),
    "jaipur": ("IN",),
    "kochi": ("IN",),
    "kolkata": ("IN",),
    "mumbai": ("IN",),
    "new delhi": ("IN",),
    "noida": ("IN",),
    "pune": ("IN",),
    "bali": ("ID",),
    "bandung": ("ID",),
    "bekasi": ("ID",),
    "bsd city": ("ID",),
    "denpasar": ("ID",),
    "jakarta": ("ID",),
    "medan": ("ID",),
    "semarang": ("ID",),
    "surabaya": ("ID",),
    "tangerang": ("ID",),
    "yogyakarta": ("ID",),
    "cyberjaya": ("MY",),
    "johor bahru": ("MY",),
    "kuala lumpur": ("MY",),
    "penang": ("MY",),
    "petaling jaya": ("MY",),
    "bangkok": ("TH",),
    "chiang mai": ("TH",),
    "phuket": ("TH",),
    "bgc": ("PH",),
    "cebu": ("PH",),
    "makati": ("PH",),
    "manila": ("PH",),
    "pasig": ("PH",),
    "quezon city": ("PH",),
    "taguig": ("PH",),
    "da nang": ("VN",),
    "danang": ("VN",),
    "hanoi": ("VN",),
    "ho chi minh": ("VN",),
    "ho chi minh city": ("VN",),
    "dhaka": ("BD",),
    "colombo": ("LK",),
    "islamabad": ("PK",),
    "karachi": ("PK",),
    "lahore": ("PK",),
    # East Asia. The Japanese boards write the ward, in Japanese, and there is nothing
    # ambiguous about it.
    "fukuoka": ("JP",),
    "kobe": ("JP",),
    "kyoto": ("JP",),
    "nagoya": ("JP",),
    "osaka": ("JP",),
    "sapporo": ("JP",),
    "tokyo": ("JP",),
    "yokohama": ("JP",),
    "大阪": ("JP",),
    "東京": ("JP",),
    "東京都": ("JP",),
    "東京都中央区": ("JP",),
    "静岡県裾野市": ("JP",),
    "busan": ("KR",),
    "incheon": ("KR",),
    "pangyo": ("KR",),
    "seoul": ("KR",),
    "beijing": ("CN",),
    "guangzhou": ("CN",),
    "hangzhou": ("CN",),
    "shanghai": ("CN",),
    "shenzhen": ("CN",),
    "hsinchu": ("TW",),
    "kaohsiung": ("TW",),
    "taichung": ("TW",),
    "taipei": ("TW",),
    "taipei city": ("TW",),
    # Oceania
    "adelaide": ("AU",),
    "alice springs": ("AU",),
    "brisbane": ("AU",),
    "canberra": ("AU",),
    "gold coast": ("AU",),
    "hobart": ("AU",),
    "perth": ("AU",),
    "sydney": ("AU",),
    "auckland": ("NZ",),
    "christchurch": ("NZ",),
    "wellington": ("NZ",),
    # Latin America
    "belo horizonte": ("BR",),
    "brasilia": ("BR",),
    "brasília": ("BR",),
    "campinas": ("BR",),
    "curitiba": ("BR",),
    "florianopolis": ("BR",),
    "florianópolis": ("BR",),
    "porto alegre": ("BR",),
    "recife": ("BR",),
    "rio de janeiro": ("BR",),
    "sao jose dos campos": ("BR",),
    "sao paulo": ("BR",),
    "são josé dos campos": ("BR",),
    "são paulo": ("BR",),
    "cdmx": ("MX",),
    "ciudad de méxico": ("MX",),
    "guadalajara": ("MX",),
    "merida": ("MX",),
    "mexico city": ("MX",),
    "monterrey": ("MX",),
    "mérida": ("MX",),
    "queretaro": ("MX",),
    "querétaro": ("MX",),
    "tijuana": ("MX",),
    "buenos aires": ("AR",),
    "rosario": ("AR",),
    "barranquilla": ("CO",),
    "bogota": ("CO",),
    "bogotá": ("CO",),
    "medellin": ("CO",),
    "medellín": ("CO",),
    "montevideo": ("UY",),
    "port of spain": ("TT",),
    # Middle East and Africa
    "abu dhabi": ("AE",),
    "dubai": ("AE",),
    "sharjah": ("AE",),
    "dammam": ("SA",),
    "jeddah": ("SA",),
    "riyadh": ("SA",),
    "doha": ("QA",),
    "cairo": ("EG",),
    "giza": ("EG",),
    "haifa": ("IL",),
    "herzliya": ("IL",),
    "jerusalem": ("IL",),
    "ramat gan": ("IL",),
    "tel aviv": ("IL",),
    "tel aviv-yafo": ("IL",),
    "cape town": ("ZA",),
    "durban": ("ZA",),
    "johannesburg": ("ZA",),
    "pretoria": ("ZA",),
    "abuja": ("NG",),
    "lagos": ("NG",),
    "nairobi": ("KE",),
    "casablanca": ("MA",),
    "rabat": ("MA",),
}
"""Place names a board writes with no country beside them, mapped to the countries they
can mean. A single-entry tuple is a statement; a longer one is a refusal that the
employer's home market may yet resolve. Rows are earned by a real posting, and the ones
*rejected* matter as much as the ones accepted — see PROGRESS."""
